###############################################################################
# Simulation script for ALDEC Riviera_PRO simulator 
#
# 1. Ensure that the need QUARTUS or VIVADO libraries are in place.
#    (see ALDEC, QUARTUS_LIB and VIVADO_LIB parameters below)
# 2. Delete all local LIB folders (to have a clean basis)
# 3. Start Riviera-Pro from the folder where this TCL script is located.
# 4. Start simulation at RIVIERA_PRO TCL console
#    > source sim.tcl
###############################################################################


###############################################################################
# The following lines may need to be changed
###############################################################################

set VIVADO_LIB ${aldec}/vlib/VIVADO/2017.3

# top-level entity
set top cplx_weight_tb

# folder for files generated by simulator
set SIMDIR "simulator"

###############################################################################
# DO NOT EDIT MODIFY the following line
###############################################################################
if ![file isdirectory $VIVADO_LIB] {
  error "Path to VIVADO libraries not found - please provide global variable VIVADO"
}

# Map Vivado libraries
#amap secureip $VIVADO_LIB/secureip
#amap unifast $VIVADO_LIB/unifast
#amap unimacro $VIVADO_LIB/unimacro
amap unisim $VIVADO_LIB/unisim
#amap xpm $VIVADO_LIB/xpm

# Create work library
alib work [file join $SIMDIR work]

# Compile BASELIB files
alib baselib [file join $SIMDIR baselib]
source ../../baselib/_filelist.tcl
acom -2008 -explicit -dbg -work $LIB $filelist

# Compile DSPLIB files
alib dsplib [file join $SIMDIR dsplib]
source ../../dsplib/_filelist.tcl
acom -2008 -explicit -dbg -work $LIB $filelist
source ../../dsplib/behave/_filelist.tcl
acom -2008 -explicit -dbg -work $LIB $filelist

# Compile CPLXLIB files
alib cplxlib [file join $SIMDIR cplxlib]
source ../../cplxlib/_filelist.tcl
acom -2008 -explicit -dbg -work $LIB $filelist

# Compile testbench files
set files [list]
lappend files [ file normalize ../cplx_stimuli.vhdl ]
lappend files [ file normalize ../cplx_logger.vhdl ]
lappend files [ file normalize ${top}.vhdl ]
acom -2008 -explicit -dbg $files

# Compile testbench files
acom -2008 -dbg -explicit $top.vhdl

# Run Riviera_PRO simulator
asim +access +r -t ps -dbg -asdbtemp $SIMDIR -dataset $SIMDIR -ieee_nowarn $top

do wave.tcl
run
